---
#################################
#################################
######### Auto Comment ##########
#################################
#################################
name: Auto Comment
on: [issues] #comments on the issues that someone has replied "!assign" to.

###############
# Set the Job #
###############
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Comment
        uses: wow-actions/auto-comment@v1.1.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #[below] when the issue is assigned to someone these imojies/ reactions are automatically added to the reply post.
          issuesAssignedReactions: 'hooray, +1' 
          #[below] when the issue is assigned to someone this reply post is generated automatically.
          issuesAssignedComment: |
            👋 You've been assigned this issue, Please fork the repository and create a branch to work on the issue assigned here 💻. When you are done make a Pull Request. Good Luck!
